#!/usr/bin/env bash
#
# bootstrap.sh — first-boot setup for a Churner preview host (design spec §7).
#
# Fetched and run by the preview host's UserData, which is the ONLY thing the
# rendered CloudFormation / Terraform body carries: the stack passes the
# module's coordinates in the environment and hands over to this file, so the
# copy a customer reviews in the repository is byte-for-byte the copy the host
# runs. Inlining a few hundred lines of shell into a template would make those
# two different files.
#
# ## The integrity chain
#
# UserData fetches this file from a PINNED tag and verifies it against the
# `PreviewScriptsSha256` stack parameter BEFORE running it. Everything this
# file goes on to fetch — the reaper, its two units, the Caddyfile template,
# and the Caddy release tarball — is verified against the digest table below.
# The chain therefore has exactly one root of trust (a digest the customer can
# read in their own stack parameters) and no unverified hop: without it, a bad
# commit on a moving branch would execute as root on every preview host that
# booted after it.
#
# The table is generated by `scripts/preview-stack-digests.sh` and asserted
# against the repository by a test in `shared/tests/preview-stack.test.ts`, so
# editing one of those files without regenerating the table fails CI rather
# than failing at 3am on a customer's host.
#
# What it installs:
#   - Docker (preview containers) and the SSM agent (already present on
#     AL2023, enabled here so a fresh AMI cannot arrive without it);
#   - Caddy, as a plain reverse proxy on port 80. TLS is terminated at the
#     ALB with the module's `*.preview.<domain>` certificate, so `auto_https`
#     is OFF — a host that tried to obtain its own certificate would fail
#     forever behind a load balancer it cannot see the DNS challenge through;
#   - the per-PR route directory `/etc/caddy/preview-routes`, which the deploy
#     workflow drops one `<pr>.caddy` file into and the reaper removes;
#   - the TTL reaper and its hourly systemd timer.
#
# Written for bash 3.2 (no associative arrays, no `mapfile`, no `${x^^}`) so
# `bash -n` on a developer's macOS is the same check CI runs.
#
# Idempotent: re-running it re-installs the units and rewrites the config,
# which is what a re-bootstrap after an AMI change should do.

set -euo pipefail

log() { echo "[churner-preview-bootstrap] $*"; }
die() { echo "[churner-preview-bootstrap] $*" >&2; exit 1; }

# --- Pinned artefact digests ------------------------------------------------
#
# Regenerate the four SHA256_ lines with `scripts/preview-stack-digests.sh`.
#
# The Caddy tarball is pinned by SHA-512 because that is what the Caddy
# project publishes in its release `checksums.txt` — a digest upstream vouches
# for is better provenance than one we computed by downloading the same bytes
# once. The two values below are copied verbatim from:
#
#   https://github.com/caddyserver/caddy/releases/download/v2.11.4/caddy_2.11.4_checksums.txt
#
# CADDY_VERSION and those two digests move TOGETHER, always: a version bumped
# without re-pinning fails `verify_digest` on every host, which is the
# intended failure — the alternative is a host silently running a build
# nobody checked.
CADDY_VERSION="2.11.4"
#
# BEGIN CHURNER PREVIEW DIGESTS
SHA256_REAPER_SH="555c04100a2f5c81409ad7054c2a6642d7d9febd666ec26bf78b1518eb54fda1"
SHA256_REAPER_SERVICE="a6afc363ce5358b5254cbfbd92d47b35431be34bb439c358eb7c30eb3a62655b"
SHA256_REAPER_TIMER="017c6dc699ff5c9766f7f85ee3495eac8e899ebbaef5614abdc5270606555203"
SHA256_CADDYFILE_TMPL="81e6afbea2b72de5435da0286ddf11efb665e46a8a1fab0c20ae2b5ff0e7af61"
SHA512_CADDY_LINUX_ARM64="d5a7c423853c24a799765e0e8210d5c7c22a8f56ed37a3cae2fb9f58be138853c02b4efd6b59d576e6d8c7c0d30b9c1592deeaa6a536ff69bcca23b8c1ea709c"
SHA512_CADDY_LINUX_AMD64="8220d1f013b6f27510247b2360c9e0ca9f018feebd82515f07635318b34ff9777ccc8fd0b6e6f2486ce3a33fe389fbb7db12d05baa474f4587509fb4f5ebf1c9"
# END CHURNER PREVIEW DIGESTS

verify_digest() {
  # verify_digest <file> <expected> <sha256sum|sha512sum>
  actual="$("$3" "$1" | cut -d' ' -f1)"
  if [ "$actual" != "$2" ]; then
    die "checksum mismatch for $1 (expected $2, got $actual) — refusing to continue"
  fi
}

fetch_verified() {
  # fetch_verified <url-path> <destination> <expected-sha256>
  curl -fsSL "${SCRIPTS_BASE_URL}/$1" -o "$2"
  verify_digest "$2" "$3" sha256sum
}

# --- Inputs -----------------------------------------------------------------
#
# Every one of these is written by the stack's UserData. They are re-checked
# here rather than assumed: a host that boots with an empty domain would serve
# every preview under the wrong name, and the failure would look like DNS.

SCRIPTS_BASE_URL="${CHURNER_SCRIPTS_BASE_URL:-}"
PREVIEW_DOMAIN="${CHURNER_PREVIEW_DOMAIN:-}"
TTL_HOURS="${CHURNER_PREVIEW_TTL_HOURS:-48}"
PROJECT_KEY="${CHURNER_PROJECT_KEY:-}"
TRACKER_URL="${CHURNER_TRACKER_URL:-https://churner.ai}"
SECRETS_PREFIX="${CHURNER_SECRETS_PREFIX:-}"
DB_SECRET_NAME="${CHURNER_DB_SECRET_NAME:-}"
TOKEN_SECRET_NAME="${CHURNER_TOKEN_SECRET_NAME:-}"
AWS_REGION_NAME="${CHURNER_AWS_REGION:-}"
MAX_OPEN_PREVIEWS="${CHURNER_MAX_OPEN_PREVIEWS:-}"

# CloudFormation resource signalling. Empty under Terraform, which has no
# equivalent — there the host reports readiness by registering with SSM.
CFN_STACK="${CHURNER_CFN_STACK:-}"
CFN_RESOURCE="${CHURNER_CFN_RESOURCE:-}"

ROUTES_DIR="${CHURNER_ROUTES_DIR:-/etc/caddy/preview-routes}"
CONFIG_DIR=/etc/churner-preview

# --- CloudFormation signal --------------------------------------------------
#
# Installed BEFORE the first thing that can fail, so a stack whose host cannot
# bootstrap fails in minutes with the reason in the console rather than
# reporting CREATE_COMPLETE on a host serving nothing.

CFN_SIGNAL_SENT=0
signal_cfn() {
  [ -n "$CFN_STACK" ] || return 0
  [ "$CFN_SIGNAL_SENT" = "0" ] || return 0
  CFN_SIGNAL_SENT=1
  cfn_bin=/opt/aws/bin/cfn-signal
  [ -x "$cfn_bin" ] || cfn_bin="$(command -v cfn-signal || true)"
  if [ -z "$cfn_bin" ]; then
    echo "[churner-preview-bootstrap] cfn-signal is not installed; cannot report status $1" >&2
    return 0
  fi
  "$cfn_bin" --exit-code "$1" \
    --stack "$CFN_STACK" \
    --resource "$CFN_RESOURCE" \
    --region "$AWS_REGION_NAME" || true
}
trap 'rc=$?; signal_cfn "$rc"' EXIT

[ -n "$SCRIPTS_BASE_URL" ] || die "CHURNER_SCRIPTS_BASE_URL is required"
[ -n "$PREVIEW_DOMAIN" ] || die "CHURNER_PREVIEW_DOMAIN is required"
[ -n "$PROJECT_KEY" ] || die "CHURNER_PROJECT_KEY is required"
[ -n "$SECRETS_PREFIX" ] || die "CHURNER_SECRETS_PREFIX is required"
[ -n "$DB_SECRET_NAME" ] || die "CHURNER_DB_SECRET_NAME is required"
[ -n "$TOKEN_SECRET_NAME" ] || die "CHURNER_TOKEN_SECRET_NAME is required"

log "bootstrapping preview host for ${PROJECT_KEY} at ${PREVIEW_DOMAIN}"

# --- Packages ---------------------------------------------------------------
#
# Output is NOT redirected: when this fails it is the only line that says why,
# and it reaches the console log through cloud-init.

# `awscli-2` is NOT optional: the reaper's every step goes through it
# (`aws secretsmanager get-secret-value` for both the database credentials and
# the preview token). AL2023 usually ships it, but a host that arrives without
# it would sweep hourly, read no secrets, and drop nothing — silently.
log "installing packages"
dnf install -y docker postgresql16 tar gzip jq awscli-2 aws-cfn-bootstrap \
  || dnf install -y docker postgresql15 tar gzip jq awscli-2 aws-cfn-bootstrap

systemctl enable --now docker
systemctl enable --now amazon-ssm-agent 2>/dev/null || true

# --- Caddy ------------------------------------------------------------------
#
# Installed from the upstream release tarball rather than a distribution
# package: AL2023 carries no Caddy, and the alternative (enabling a Fedora
# COPR on Amazon Linux) is a repository the customer did not choose.

ARCH="$(uname -m)"
case "$ARCH" in
  aarch64|arm64) CADDY_ARCH=arm64; CADDY_SHA512="$SHA512_CADDY_LINUX_ARM64" ;;
  x86_64|amd64)  CADDY_ARCH=amd64; CADDY_SHA512="$SHA512_CADDY_LINUX_AMD64" ;;
  *) die "unsupported architecture: $ARCH" ;;
esac

if ! command -v caddy >/dev/null 2>&1; then
  log "installing caddy ${CADDY_VERSION} (${CADDY_ARCH})"
  CADDY_TMP="$(mktemp -d)"
  curl -fsSL \
    "https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_${CADDY_ARCH}.tar.gz" \
    -o "${CADDY_TMP}/caddy.tar.gz"
  verify_digest "${CADDY_TMP}/caddy.tar.gz" "$CADDY_SHA512" sha512sum
  tar -xzf "${CADDY_TMP}/caddy.tar.gz" -C "$CADDY_TMP" caddy
  install -m 0755 "${CADDY_TMP}/caddy" /usr/local/bin/caddy
  rm -rf "$CADDY_TMP"
fi

id caddy >/dev/null 2>&1 || useradd --system --home /var/lib/caddy --shell /usr/sbin/nologin caddy
install -d -m 0755 /etc/caddy
install -d -m 0755 "$ROUTES_DIR"
install -d -o caddy -g caddy -m 0750 /var/lib/caddy

# The Caddyfile ends with `import <routes>/*.caddy`, and some Caddy versions
# treat a glob matching zero files as a configuration error — which would mean
# a host with no previews open refuses to start, i.e. every host on its first
# boot. A comment-only placeholder makes the empty case identical to the busy
# one. The reaper only ever removes `pr-<n>.caddy`, so it survives.
cat > "${ROUTES_DIR}/00-placeholder.caddy" <<'PLACEHOLDER'
# Placeholder so the route glob always matches. Per-PR routes are written
# beside this file as pr-<number>.caddy and removed by the TTL reaper.
PLACEHOLDER

log "writing the Caddyfile"
fetch_verified proxy/Caddyfile.tmpl /etc/caddy/Caddyfile.tmpl "$SHA256_CADDYFILE_TMPL"
sed -e "s|@@ROUTES_DIR@@|${ROUTES_DIR}|g" \
    -e "s|@@PREVIEW_DOMAIN@@|${PREVIEW_DOMAIN}|g" \
    /etc/caddy/Caddyfile.tmpl > /etc/caddy/Caddyfile

cat > /etc/systemd/system/caddy.service <<'UNIT'
[Unit]
Description=Caddy reverse proxy for Churner previews
After=network-online.target
Wants=network-online.target

[Service]
User=caddy
Group=caddy
ExecStart=/usr/local/bin/caddy run --environ --config /etc/caddy/Caddyfile
# SIGUSR1, not `caddy reload`: the Caddyfile sets `admin off`, so the reload
# subcommand — which POSTs to the admin API — has nothing to talk to and every
# route add/remove would be a silent no-op. `caddy run` re-reads its config on
# SIGUSR1 with no admin endpoint at all.
#
# SIGUSR1 config reload landed in Caddy 2.11.0. On an older build the signal
# is not handled and the reload is the same silent no-op by a different
# route — which is why CADDY_VERSION above is 2.11.x and a test asserts it.
ExecReload=/bin/kill -USR1 $MAINPID
Restart=on-failure
RestartSec=5s
# Port 80 is below 1024 and Caddy runs unprivileged.
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
UNIT

# --- Shared configuration ---------------------------------------------------
#
# One file every later process reads, so the deploy workflow's SSM commands
# and the reaper agree about where things are without re-deriving them.

install -d -m 0755 "$CONFIG_DIR"
cat > "${CONFIG_DIR}/env" <<CONFIG
CHURNER_PROJECT_KEY=${PROJECT_KEY}
CHURNER_TRACKER_URL=${TRACKER_URL}
CHURNER_PREVIEW_DOMAIN=${PREVIEW_DOMAIN}
CHURNER_PREVIEW_TTL_HOURS=${TTL_HOURS}
CHURNER_SECRETS_PREFIX=${SECRETS_PREFIX}
CHURNER_DB_SECRET_NAME=${DB_SECRET_NAME}
CHURNER_TOKEN_SECRET_NAME=${TOKEN_SECRET_NAME}
CHURNER_AWS_REGION=${AWS_REGION_NAME}
CHURNER_ROUTES_DIR=${ROUTES_DIR}
CHURNER_MAX_OPEN_PREVIEWS=${MAX_OPEN_PREVIEWS}
CONFIG
# The file names secrets; it does not contain them. Still 0640 — nothing
# outside root and the reaper has any business reading the host's topology.
chmod 0640 "${CONFIG_DIR}/env"

# --- Reaper -----------------------------------------------------------------

log "installing the TTL reaper"
fetch_verified host/reaper.sh /usr/local/bin/churner-preview-reaper.sh "$SHA256_REAPER_SH"
chmod 0755 /usr/local/bin/churner-preview-reaper.sh
fetch_verified host/reaper.service /etc/systemd/system/churner-preview-reaper.service "$SHA256_REAPER_SERVICE"
fetch_verified host/reaper.timer /etc/systemd/system/churner-preview-reaper.timer "$SHA256_REAPER_TIMER"

systemctl daemon-reload
systemctl enable --now caddy
systemctl enable --now churner-preview-reaper.timer

log "done — previews will answer at <pr>.${PREVIEW_DOMAIN}"
